================================================== cannot_call_non_func
exit_code: 103
--------------------------------------------------
"test"();
--------------------------------------------------
--------------------------------------------------
runtime_errors/cannot_call_non_func.sd:1:1: can't call 'string' as a function
================================================== undefined
exit_code: 103
--------------------------------------------------
not_defined;
--------------------------------------------------
--------------------------------------------------
runtime_errors/undefined.sd:1:1: 'not_defined' is not defined
================================================== undefined_assignment
exit_code: 103
--------------------------------------------------
not_defined = 3;
--------------------------------------------------
--------------------------------------------------
runtime_errors/undefined_assignment.sd:1:1: 'not_defined' is not defined
================================================== invalid_bind_target
exit_code: 103
--------------------------------------------------
1 := 1;
--------------------------------------------------
--------------------------------------------------
runtime_errors/invalid_bind_target.sd:1:1: cannot bind to an integer literal
================================================== already_in_scope1
exit_code: 103
--------------------------------------------------
x := 1;
x := 1;
--------------------------------------------------
--------------------------------------------------
runtime_errors/already_in_scope1.sd:2:1: 'x' is already defined in the current scope at [1:1]
================================================== already_in_scope2
exit_code: 103
--------------------------------------------------
x := 1;
fn x(){}
--------------------------------------------------
--------------------------------------------------
runtime_errors/already_in_scope2.sd:2:4: 'x' is already defined in the current scope at [1:1]
================================================== already_in_scope3
exit_code: 103
--------------------------------------------------
fn x(){}
x := 1;
--------------------------------------------------
--------------------------------------------------
runtime_errors/already_in_scope3.sd:2:1: 'x' is already defined in the current scope at [1:4]
================================================== arg_num_mismatch
exit_code: 103
--------------------------------------------------
fn f(a, b){}
f(1);
--------------------------------------------------
--------------------------------------------------
runtime_errors/arg_num_mismatch.sd:2:1: expected 2 arguments, got 1
================================================== incorrect_type
exit_code: 103
--------------------------------------------------
{1: ""};
--------------------------------------------------
--------------------------------------------------
runtime_errors/incorrect_type.sd:1:2: property name must be 'string', got 'int'
================================================== dup_arg_names
exit_code: 103
--------------------------------------------------
fn f(a, a){}
f(1, 2);
--------------------------------------------------
--------------------------------------------------
runtime_errors/dup_arg_names.sd:1:9: in 'f': 'a' is already defined in the current scope at [1:6]
Stacktrace:
  runtime_errors/dup_arg_names.sd:2:1: in '<root>'
================================================== add_bad_types1
exit_code: 103
--------------------------------------------------
true + {};
--------------------------------------------------
--------------------------------------------------
runtime_errors/add_bad_types1.sd:1:6: can't apply '+' to 'bool' and 'object'
================================================== add_bad_types2
exit_code: 103
--------------------------------------------------
1 + 2 * [];
--------------------------------------------------
--------------------------------------------------
runtime_errors/add_bad_types2.sd:1:7: can't apply '*' to 'int' and 'list'
================================================== bad_type_equality
exit_code: 103
--------------------------------------------------
[] == {};
--------------------------------------------------
--------------------------------------------------
runtime_errors/bad_type_equality.sd:1:4: can't apply '==' to 'list' and 'object'
================================================== op_assign_lhs_not_var
exit_code: 103
--------------------------------------------------
1 += 1;
--------------------------------------------------
--------------------------------------------------
runtime_errors/op_assign_lhs_not_var.sd:1:1: the LHS of an operation-assignment must be a variable
================================================== op_assign_bad_types
exit_code: 103
--------------------------------------------------
x := 1;
x += "";
--------------------------------------------------
--------------------------------------------------
runtime_errors/op_assign_bad_types.sd:2:3: can't apply '+' to 'int' and 'string'
================================================== return_outside_function
exit_code: 103
--------------------------------------------------
return null;
--------------------------------------------------
--------------------------------------------------
runtime_errors/return_outside_function.sd:1:1: 'return' can't be used outside of a function
================================================== value_not_indexable
exit_code: 103
--------------------------------------------------
1[2];
--------------------------------------------------
--------------------------------------------------
runtime_errors/value_not_indexable.sd:1:1: only 'list's, 'object's or 'string's can be indexed
================================================== out_of_string_bounds
exit_code: 103
--------------------------------------------------
"abc"[5];
--------------------------------------------------
--------------------------------------------------
runtime_errors/out_of_string_bounds.sd:1:1: index '5' is outside the string bounds
================================================== out_of_list_bounds
exit_code: 103
--------------------------------------------------
[1, 2, 3][5];
--------------------------------------------------
--------------------------------------------------
runtime_errors/out_of_list_bounds.sd:1:1: index '5' is outside the list bounds
================================================== no_such_key
exit_code: 103
--------------------------------------------------
{}["a"];
--------------------------------------------------
--------------------------------------------------
runtime_errors/no_such_key.sd:1:1: object doesn't contain the key 'a'
================================================== negative_string_index
exit_code: 103
--------------------------------------------------
"abc"[0-1];
--------------------------------------------------
--------------------------------------------------
runtime_errors/negative_string_index.sd:1:1: string index can't be negative
================================================== negative_list_index
exit_code: 103
--------------------------------------------------
[1, 2, 3][0-1];
--------------------------------------------------
--------------------------------------------------
runtime_errors/negative_list_index.sd:1:1: list index can't be negative
==================================================
