================================================== cannot_call_non_func
exit_code: 103
--------------------------------------------------
"test"();
--------------------------------------------------
--------------------------------------------------
runtime_errors/cannot_call_non_func.sd:1:1: can't call 'string' as a function
================================================== undefined
exit_code: 103
--------------------------------------------------
not_defined;
--------------------------------------------------
--------------------------------------------------
runtime_errors/undefined.sd:1:1: 'not_defined' is not defined
================================================== undefined_assignment
exit_code: 103
--------------------------------------------------
not_defined = 3;
--------------------------------------------------
--------------------------------------------------
runtime_errors/undefined_assignment.sd:1:1: 'not_defined' is not defined
================================================== invalid_bind_target
exit_code: 103
--------------------------------------------------
1 := 1;
--------------------------------------------------
--------------------------------------------------
runtime_errors/invalid_bind_target.sd:1:1: cannot bind to an integer literal
================================================== already_in_scope1
exit_code: 103
--------------------------------------------------
x := 1;
x := 1;
--------------------------------------------------
--------------------------------------------------
runtime_errors/already_in_scope1.sd:2:1: 'x' is already defined in the current scope
================================================== already_in_scope2
exit_code: 103
--------------------------------------------------
x := 1;
fn x(){}
--------------------------------------------------
--------------------------------------------------
runtime_errors/already_in_scope2.sd:2:4: 'x' is already defined in the current scope
================================================== already_in_scope3
exit_code: 103
--------------------------------------------------
fn x(){}
x := 1;
--------------------------------------------------
--------------------------------------------------
runtime_errors/already_in_scope3.sd:2:1: 'x' is already defined in the current scope
================================================== arg_num_mismatch
exit_code: 103
--------------------------------------------------
fn f(a, b){}
f(1);
--------------------------------------------------
--------------------------------------------------
runtime_errors/arg_num_mismatch.sd:2:1: expected 2 arguments, got 1
================================================== incorrect_type
exit_code: 103
--------------------------------------------------
{1: ""};
--------------------------------------------------
--------------------------------------------------
runtime_errors/incorrect_type.sd:1:2: property name must be 'string', got 'int'
==================================================
